### ISSUE TITLE
[Assignment 3]Should normals be computed in CPU side or GPU side?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#101]
Should normals be computed in CPU side or GPU side?
Thank you!

**Comment by danielepanozzo** [comment]
The normals should also be computed in the shader (GPU side), by transforming the normals of the rest pose. Note that the normals should not be transformed using the same transformation that you use for the coordinates, see https://cs.nyu.edu/~panozzo/cg18/Slides/10%20-%20Texture%20Mapping.pdf.

**Comment by LihengGong** [comment]
Thank you Prof.
My confusion here is that if normals are computed in shader(GPU side), it seems that this "computing normal" process will happen for each rendering; while if normals are computed in CPU side, it seems that we only need to compute normals when loading the OFF data.

**Comment by danielepanozzo** [comment]
The normals *for the rest pose of the object* should be either read from the OFF file (if available), or computed once on the CPU side after reading the OFF file. After this, the normals should be transformed (together with the vertex position) inside the shader to account for the fact that the object is moved/scale/rotated by the transformation attached to each object. This second step should happen in the shader.

Hope this makes it more clear!

**Comment by LihengGong** [comment]
Got it. Thank you Prof. Have a nice weekend.
