### ISSUE TITLE
confusion in Assignment3 1.1

### ISSUE THREAD

**Issue by peiyueY** [danielepanozzo/cg-old#103]
Hi, professor. I'm not sure what we are supposed to implement in 1.1. It says Implement an interactive application that allows to **add, edit and delete** 3D meshes. Does "edit" mean task 1.2 or other kind of edit? And for "delete" part, does it mean delete any selected object or just delete all objects?

Thanks

**Comment by danielepanozzo** [comment]
Edit means being able to change position, scale, or rotation of each object independently.
Delete means removing a single object from the scene.
