### ISSUE TITLE
[Assignment 3] Do we have any requirement regarding rotation?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#105]
Do we have any requirement regarding rotation?

For example
- should a 3d object rotate around its centroid?
- should the rotation align with X, Y, or Z axis or should the rotation align with any arbitrary vector?

Thank you!

**Comment by danielepanozzo** [comment]
They should rotate around their centroid as in the previous exercise. You can decide the axis of rotation.

**Comment by LihengGong** [comment]
Thank you prof.
