### ISSUE TITLE
[Assignment 3]Phong shading V.S. flat shading: how to arrange normals?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#106]
Phong shading V.S. flat shading: how to arrange normals?

My understanding is:
- for Phong shading, the average normal is used for a vertex(as per description in our assignment: `the normal of the vertex of a mesh should be the average of the normals of the faces touching it`.)
- for flat shading, each triangle has its own normal.

My problem:
- I can compute the average normal for each vertex(I save one normal for each vetex) and I can complete Phong shading.
- I can also compute the specific normal for each triangle(but I need to save multiple normals for each vertex) and I can complete blank shading.
- But how can I save the pre-computed normals so that I can both use blank shading(each vertext has its own normals) and Phone shading(only averaged normal is required)?

**Comment by danielepanozzo** [comment]
If I understand the question correctly, you are saying that you could get both flat shading and Phong shading to work, but you would like to have an elegant way of switching between the 2?

If that is the question, there is no way to do both and easily switch. You will need two VBOs, one for each type of normal.

**Comment by LihengGong** [comment]
Yes, prof. That's exactly my question.
I got your point. Thank you and have a good night
