### ISSUE TITLE
Office Hour avaiable on Wednesday (tomorrow)?

### ISSUE THREAD

**Issue by alex-s-hong** [danielepanozzo/cg-old#107]
Hello, professor,
I am stuck in the assignment, and I really don't know how to fix or proceed...
Do you have any time for tomorrow for office hour?

**Comment by danielepanozzo** [comment]
Let's organize this meeting by email. Tomorrow I can only do 6PM for 30 minutes. 

Hanxiao also has office hours tomorrow:
Wednesdays, 3pm-4pm and by appointment, 60 5th Ave, 5th Floor
