### ISSUE TITLE
Field of view in perspective projection matrix

### ISSUE THREAD

**Issue by txstc55** [danielepanozzo/cg-old#108]
For project 3, when moving the camera around, should the viewing angle be the same across all the plane?

For example: if we are always making the camera to view the box from -1, -1, 1 to 1, 1, -1, and the screen we are looking at is the near side of the box, then when you put camera really far away, it will have the same effect as a orthographic projection. However, if we define the viewing angle to be the same, then the further away, the smaller the object.

**Comment by danielepanozzo** [comment]
The projective transformation should be the same, independently from where you are on the plane. If you move the camera further away from the object (while pointing directly at it), the object should become smaller when perspective projection is used (and stay the same with orthographic).
