### ISSUE TITLE
Assignment submision

### ISSUE THREAD

**Issue by ypiadyk** [danielepanozzo/cg-old#11]
Dear Daniele and Zhenyi.

I wanted to present my completed Assignment 1 today during the office hours but I couldn't find Zhenyi at Room 412 Warren Weaver Hall. There were several pools concerning the office hours change, so what are the final (current) office hours?

Also, I'm unable to create a private repository at NYUCG2016 in order to commit and push my source code. The error is:
Your org is out of private repositories. Please contact an Owner and ask them to upgrade.

How can I submit the assignment?

Thank you.

Yurii Piadyk

**Comment by iqranawab** [comment]
Same case here, org out of private repositories.

**Comment by danielepanozzo** [comment]
Zhenyi is looking into this problem now, she will send un update ASAP.
