### ISSUE TITLE
1.3 What does "always point to the origin" mean?

### ISSUE THREAD

**Issue by Bhavani-Bhamidipaty** [danielepanozzo/cg-old#110]
In 1.3, "always point to the origin" would mean that when camera is moved, the angle of the camera's viewing should change to compensate so that it continues to point at origin. Is this the correct interpretation of the requirement? Or does it simply say that at no point should the camera not face -z direction ?

**Comment by danielepanozzo** [comment]
The gaze (viewing) direction g in the camera transformation should be a vector pointing from the eye (e) to the origin of the world reference system (which is the center of your scene).

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/6785134/48594644-5ee31b00-e91f-11e8-9836-8c4757b78fa3.png">

**Comment by Bhavani-Bhamidipaty** [comment]
Thank you for the clarification !

**Comment by Bhavani-Bhamidipaty** [comment]
Thank you for the clarification !
