### ISSUE TITLE
External libraries for project

### ISSUE THREAD

**Issue by mun1r0b0t** [danielepanozzo/cg-old#114]
Hello professor,

Do we need to include the external libraries as git sub-modules or is it okay to specify in the report that particular libraries are required for the application to compile?

Thanks.

**Comment by danielepanozzo** [comment]
It is ok to just write it in the report. However, remember to send me an updated project proposal if you want to use external libraries, since every external library that you use must be listed in the approved project proposal.

**Comment by mun1r0b0t** [comment]
Thank you. I've already mentioned that I will be using Freetype for fonts in my proposal. Other than that, I'm only using Eigen, glew and glfw. If something else is required, I'll send a new proposal.
