### ISSUE TITLE
Assignment 1-4

### ISSUE THREAD

**Issue by iqranawab** [danielepanozzo/cg-old#12]
After storing the data from the mesh in ArrayXXf , when i'm trying to traverse in the same and check if the point is inside the triangle or not.
I'm getting an error
"Assertion failed: (row >= 0 && row < rows() && col >= 0 && col < cols()), function operator(), file /Users/Iqra/Assignment1/Assignment_1/../ext/eigen/Eigen/src/Core/DenseCoeffsBase.h, line 337."

Any clue as to how to solve this error?

Thanks

**Comment by danielepanozzo** [comment]
You are accessing an element that is outside the Array. The assertion is telling you that the row[column] index is either negative or larger than the total number of rows [columns].
