### ISSUE TITLE
Intel TBB linux or mac install?

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/cg-old#13]
I want to try leveraging Intel TBB for the extra credit.  In the [TBB download page](https://www.threadingbuildingblocks.org/download) you can choose windows/mac/linux download.

I'm concerned that if I download for my local OS, Mac, it will break the travis ci job.  What's the recommended setup?

**Comment by ypiadyk** [comment]
You can make compilation using tbb optional in CMakeLists.txt:

OPTION(USE_TBB "Use intel tbb parallelization" ON)

IF(USE_TBB)
    ADD_DEFINITIONS(-DTBB)
    target_link_libraries(${PROJECT_NAME}_bin tbb)
ENDIF(USE_TBB)

And in main.cpp or however your code is structured:

#ifdef TBB
    #include "tbb/tbb.h"
#endif

and so on.

Then use 
cmake -DUSE_TBB=OFF ../
if necessary.

**Comment by ypiadyk** [comment]
Or even simpler:
 cmake -DTBB ../
to switch on. By default it will be off (no TBB macro defined in source code). And remove everything I wrote earlier about CMakeLists.txt. The first method is cmake-gui friendly though.

**Comment by danielepanozzo** [comment]
For TBB you do not have to worry about the build. Just pick your favorite OS and write in the readme that it only run on that OS.

The solution of ypiadyk is ideal, thank you for sharing the nice cmake snippet!
