### ISSUE TITLE
OFF format

### ISSUE THREAD

**Issue by jw3877** [danielepanozzo/cg-old#14]
For this assignment, is it safe to assume that the number of vertices for each face listed in the OFF file will be 3?

The OFF file example on Wikipedia gives faces defined by 4 vertices:
 4  0 1 2 3  

but we don't have to support that. Our program won't work with the cube example: 
https://en.wikipedia.org/wiki/OFF_(file_format)

**Comment by jw3877** [comment]
Also, where are the k coefficients stored if not in the OFF file?

**Comment by danielepanozzo** [comment]
Yes, it is ok to assume that the OFF only contains triangles, i.e. faces with 3 vertices.

The k coefficients are not given, you can pick whatever coefficients you like.
