### ISSUE TITLE
Loading shaders from external files

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/cg-old#15]
I can't help but want to load the shaders from external files, especially when it comes to being able to have syntax highlighting.

I'm having issues getting this to work. Here is the code I'm running:

I have a function `loadshader` which just returns the shader as a string from a file:

``` C++
#include <fstream>
#include <streambuf>
#include <sstream>

#include <iostream>

std::string loadshader(std::string fileName)
{
  std::ifstream t(fileName.c_str());
  std::stringstream buffer;
  buffer << t.rdbuf();

  std::string result = buffer.str();

  std::cout << result << std::endl;

  return result;
}
```

I've modified main.cpp to leverage this function to load the shaders from files:

``` C++
    const GLchar* vertex_shader = loadshader("../src/shaders/vertex.glsl").c_str();
    const GLchar* fragment_shader = loadshader("../src/shaders/fragment.glsl").c_str();
```

When running the code, the output correctly prints out the shader code:

> # version 150 core
> 
> in vec2 position;
> void main()
> {
>     gl_Position = vec4(position, 0.0, 1.0);
> };
> # version 150 core
> 
> out vec4 outColor;
> uniform vec3 triangleColor;
> void main()
> {
>     outColor = vec4(triangleColor, 1.0);
> };

but I get the error:
GL_INVALID_VALUE - /Users/danoved/Source/learning/cg/Assignment_2/src/lib/Helpers.cpp:15

Most likely because the shaders aren't assigned properly to the constant character pointer.

I'm positive these lines that load the shaders are all that has been modified from the original source code.

What am I doing wrong?

**Comment by danielepanozzo** [comment]
It is likely that your std::string are going out of scope and your char\* is invalid. You probably need to make a copy of the string that you get from c_str():

``` c++
std::string str ("Please split this sentence into tokens");
char * cstr = new char [str.length()+1];
std::strcpy (cstr, str.c_str());
```

http://www.cplusplus.com/reference/string/string/c_str/

**Comment by oveddan** [comment]
Thank you @danielepanozzo ! That pointed me into the right direction. I in the end just need to first assign the strings to a variable, then could just do the direct copy onto the constant char pointer.  The below worked:

``` C++
std::string vertex_shader_string = loadshader("../src/shaders/vertex.glsl");

std::string fragment_shader_string = loadshader("../src/shaders/fragment.glsl");

const GLchar* vertex_shader = vertex_shader_string.c_str();
const GLchar* fragment_shader = fragment_shader_string.c_str();
```

**Comment by danielepanozzo** [comment]
This is still dangerous and works because you are lucky :) When the strings go out of the scope both vertex_shader and fragment_shader will point to unallocated memory. 

``` c++
const GLchar* vertex_shader = vertex_shader_string.c_str();
```

Only copies the pointer, not the content. The right way to do it is to explicitly copy the char array.

**Comment by oveddan** [comment]
@danielepanozzo thank you for the suggestion, that makes sense. Will be sure to do that.
