### ISSUE TITLE
Assignment 2 - drawing edges

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/cg-old#17]
In the specification for assignment 2, all of the images show edges around the triangles being drawn.  Are we required to do this?

Should we use something like `glDrawArrays(GL_LINES ...)` to draw these edges?  Do you recommend adding a second shader program to render these edges? Or is there a simpler way, or guide somewhere with pointers on how to do this?

**Comment by danielepanozzo** [comment]
No, it is not required.

**Comment by oveddan** [comment]
thank you
