### ISSUE TITLE
For question 1, how should we turn off modes?

### ISSUE THREAD

**Issue by ll1733** [danielepanozzo/cg-old#20]
For example, pressing key ’p’ will enable delete mode, but how can we turn off this mode? Do we assume that after deleting a triangle, this mode would be automatically turned off or it is always on until we explicitly press 'p' again to turn off?

**Comment by danielepanozzo** [comment]
The mode will stay active until another mode is enabled by pressing another key.

**Comment by ll1733** [comment]
Got it, thanks very much!
