### ISSUE TITLE
Window Resize

### ISSUE THREAD

**Issue by ypiadyk** [danielepanozzo/cg-old#21]
Had to add:

    while (!glfwWindowShouldClose(window))
    {
		int width, height;
		glfwGetWindowSize(window, &width, &height);
		glViewport(0, 0, width, height);
...

For window to resize properly. Otherwise, the initial image is stuck in the left-bottom corner of the window instead of scaling together with the window (tested on MS Windows).

**Comment by danielepanozzo** [comment]
Thanks for the report. This is automatically happening on macosx, seems to be an os inconsistency in glfw.
