### ISSUE TITLE
cursor pos

### ISSUE THREAD

**Issue by jw3877** [danielepanozzo/cg-old#22]
The cursor position given by GLFW seems to be an offset from the upper left corner of the window, with (0, 0) in the upper left hand corner and (width, height) in the lower right hand corner.

For screen space, I thought that we were supposed to assume that the origin (0, 0) was located in the lower left hand corner of the window. This contradiction seems to be interfering with my screen space -> world space transformation.

Is it normal to subtract the y cursor position (given to us by GLFW) from the window height before applying the screen space -> world space transformation?

Vector4f pScreen(xpos, windowHeight - ypos, 0, 1);

**Comment by danielepanozzo** [comment]
Yes it is normal, it is just a convention that GLFW uses.
