### ISSUE TITLE
Question about scale up and down

### ISSUE THREAD

**Issue by ll1733** [danielepanozzo/cg-old#23]
For 1.2, it asks to scale the object up by 25% and then down by 25%. I'm wondering how we should interpret the scale number. When scaling up, should we use 1.25 to multiply the original V and when scaling down, should we use 0.75 to multiply? But if doing this way, scaling up once and then scaling down once would not give us the original picture, since 1.25*0.75 not equals to 1. Then should we just divide V by 1.25 when scaling down?

**Comment by danielepanozzo** [comment]
You should store a scaling value that is initially 1. Each press of the zoom in button will add 0.25 to it, and each press of the zoom out button will remove 0.25. You can then use the current scale value to scale accordingly the viewing volume.

**Comment by jw3877** [comment]
Say the scale value is initially 1 and you press the zoom in button 3 times. Now the scale value is 1.75.

If you press the zoom out button, the scale value should change to 0.75, not 1.50, correct? Otherwise "zoom out" would make the object bigger.

So we have to check if the scale value is greater than 1 before zooming out, and if so set reset it to 1 before subtracting 0.25 (and vice versa for zooming in -- if the scale value is less than 1, reset it to 1 before adding 0.25).

**Comment by ll1733** [comment]
I still think multiplying and dividing 1.25 can achieve the same effects more conveniently.

**Comment by ll1733** [comment]
Should we then keep track of separate scale value for each triangle? Since each triangle would be scaled up or down by different times.

**Comment by danielepanozzo** [comment]
The zoom in and out buttons are simply changing the current zoom level. They should make the objects bigger or smaller _with respect to the previous view_. Adding and removing a fixed number (0.25) is the most common way and it is the behavior that most application have (see for example the zoom parameter in word, excel, and powerpoint).

There is no reason to reset it to 1 every time. It is sufficient to start from 1 and then add or remove 0.25 depending on the button that it is pressed.

**Comment by ll1733** [comment]
Since each triangle may be scaled up or down by different times, should we keep track of separate scale value for each of them?

**Comment by ll1733** [comment]
Also, if I press "zoom out" for 4 times, would the scale factor be 1-0.25*4=0, such that the picture would disappear completely?

**Comment by danielepanozzo** [comment]
Yes, every triangle should have its own scale.

You can do as you prefer, you either let it disappear or you stop the scaling at 0.25.
