### ISSUE TITLE
View Control Unintuitive

### ISSUE THREAD

**Issue by ericapeng** [danielepanozzo/cg-old#25]
In 1.4 View Control, it says to support the action: 

> ’w’, ’a’, ’s’, and ’d’ should pan the view by 20% of the visible part of the scene, i.e. translate the entire scene, respectively down, right, up and left by 20% of the window size.

It seems a bit unintuitive for those keys to result in such translations since usually ’w’, ’a’, ’s’, and ’d’ would translate to the up, left, down, and right directions respectively based on how they sit on the keyboard. Is this a typo or is there a reason for the translation directions to be implemented in this specific way?

**Comment by danielepanozzo** [comment]
There is no special reason, please feel free to swap them if you find them unintuitive.
