### ISSUE TITLE
error checking and platform

### ISSUE THREAD

**Issue by jw3877** [danielepanozzo/cg-old#26]
Is it okay to have minimal error checking for the purposes of this assignment?

Also, do we have to worry about building on platforms other than linux? We can safely exclude these checks in our code:

#ifdef _WIN32
#ifdef __APPLE__

**Comment by danielepanozzo** [comment]
Yes it is ok to have minimal error checking.

It is sufficient to check if it builds on linux.

**Comment by jw3877** [comment]
Okay, I removed OSX from your travis script because it wasn't building on Mac. Only the top (linux) section of the script is in my repo now.
