### ISSUE TITLE
color mode

### ISSUE THREAD

**Issue by jw3877** [danielepanozzo/cg-old#27]
In color mode, the cursor has to be inside a triangle when the mouse is clicked in order to change the color of the closest vertex.

In other words, if the user clicks in the background area (outside of all triangles), no colors will be changed, even if there is a  vertex nearby.

Is that correct? If not, then we have to iterate through the vertices of every triangle on every click to find the closest overall vertex in the scene.

**Comment by danielepanozzo** [comment]
Both ways will be accepted, you can either select it only when clicking on a triangle or you can iterate over all vertices to find the closest one.
