### ISSUE TITLE
Compiling on Travis

### ISSUE THREAD

**Issue by ericapeng** [danielepanozzo/cg-old#28]
As specified in the General Guidelines, how should we check to make sure that our code compiles on Travis? I coded my solution on a mac and for the previous assignment, I tested my code on a Ubuntu virtual machine, but this time I had trouble getting OpenGL on it, so I was wondering if there was any other recommended ways to test our code on linux?

**Comment by mmorse1217** [comment]
Travis runs a build script on your repository whenever you push a commit to remote and tests your executable to see if it runs. In theory, we should just need to push to the private repo via git and Travis should start a build. 

That being said, I still needed to log in to Travis specifically (travisci.com) with my Github credentials and flip a switch on the private repo I made for the assignment in the NYUCG2016 organization that enabled these builds before anything happened. In the Travis page for the repo, it should indicate whether the build was successful.
