### ISSUE TITLE
Assignment 2: Preventing View Distortion

### ISSUE THREAD

**Issue by mmorse1217** [danielepanozzo/cg-old#29]
In lecture, we saw how to prevent view distortion from window resizing by applying a view matrix inside the vertex shader. Is this required as part of Assignment 2, or just nice to have? It was mentioned in passing that we "will have to do this in the assignment," but it doesn't appear explicitly in the assignment description (unless I missed it).

**Comment by danielepanozzo** [comment]
Good point. Given that I forgot to write it explicitly in Assignment 2, it will not be mandatory to do.
Note that even if you do not do it, you still have to account for the changes in the viewport for all the other steps of the exercise (picking triangles, translation, etc.). Your program should continue to work after resizing the window.
