### ISSUE TITLE
Task 1.6 Support for Keyframing

### ISSUE THREAD

**Issue by tomhsu1990** [danielepanozzo/cg-old#31]
Hi,

Is Task 1.6  covered in the lecture? I cannot remember the keyword "keyframe". I'm not sure how to  start doing this Task. Any hints? Thank you!

**Comment by danielepanozzo** [comment]
No, we did not cover it yet in the lecture. 

For keyframing you need to have the possibility to save at least two states of all primitives (for example their position). After the two states are saved, you can create an animation interpolating between them. You can find a simple example for translation here: https://www.youtube.com/watch?v=ERH7uoGBWPk

Of course you don’t need the fancy UI to edit the timeline — just 3 keys for “save keyframe 1”, “save keyframe 2” and “play” will be sufficient.
