### ISSUE TITLE
Do we have source code for Assignment3 to work on?

### ISSUE THREAD

**Issue by ll1733** [danielepanozzo/cg-old#32]
The page for assignment 3 says "clone the repository: https://github.com/NYUCG2016/Assignment3", but I didn't see this repository posted yet. So I'm wondering whether we have such repository to start with or we should just modify the code for assignment 2.

**Comment by danielepanozzo** [comment]
Sorry for the typo. You should start from the same repository used for Assignment 2:
https://github.com/NYUCG2016/Assignment2
