### ISSUE TITLE
Assignment 3 Task 1.1 & 1.4

### ISSUE THREAD

**Issue by tomhsu1990** [danielepanozzo/cg-old#34]
Hi,

I have a question about Task 1.1. In the first sentence, I'm not sure the "edit" operation. Does it mean the operations in Task 1.2?
In the Task 1.4, ... and at the end all objects should go back to their previous state. ... Does "their previous state" mean the start position or it should follow the same path and return to the start position?

**Comment by danielepanozzo** [comment]
"Edit" refers to the operations in Task 1.2.

Task 1.4: by "previous state" I mean their original position before they started moving. They can just "teleport" back to the previous state, it is not required to take them back following the reverse path.

**Comment by tomhsu1990** [comment]
Thanks! Originally, I thought we need to do something like what you have done in class to transform the object by using Blender. Glad to know we don't have to : )
