### ISSUE TITLE
triangle normal

### ISSUE THREAD

**Issue by jw3877** [danielepanozzo/cg-old#35]
To get the normal of a triangle consisting of points a, b, and c:
((b - a).cross(c - a)).normalized();

How do the ordering of vertices determine the direction of the normal? Could you post a quick reminder of the rule with an example?

**Comment by danielepanozzo** [comment]
You can find more info on the cross product here: https://en.wikipedia.org/wiki/Cross_product

https://en.wikipedia.org/wiki/File:Right_hand_rule_cross_product.svg

**Comment by jw3877** [comment]
I rearranged the ordering of the face indices in my unitCube.OFF file to get the desired normals. The triangles that form the front of the cube now have normal (0, 0, 1), the triangles that form the back of the cube have normal (0, 0, -1), the left side (-1, 0, 0), etc.

1) The first thing I notice is how painful and manual this process is, even for a simple cube. Are the normals usually read in from a separate file or does the creator of the OFF file give some indication of ordering to be used when computing the normals (ie, which is a, b, c in equation above)?

2) When computing the normals using the line of code I posted above, I seem to be getting negative zero in some cases:
normal: (-0, 0, 1)
normal: (0, -0, 1)

Is this expected or something is wrong?

**Comment by danielepanozzo** [comment]
1) Usually the vertices of each triangles are sorted in counterclockwise [clockwise] order inside OFF files so that all the normals will point in the outward [inward] direction if you take the cross product using the same vertex order for all triangles.

2) It is normal to have small numerical errors when you are using floating point numbers.
