### ISSUE TITLE
Assignment 3 Task 1.2

### ISSUE THREAD

**Issue by tomhsu1990** [danielepanozzo/cg-old#36]
Hi,

In Task 1.2, the first rendering option is Wireframe. Since we have cubes, for simplicity should we just use triangles to represent a cube? Or we have to use squares to represent a cube? And another question is that we can have fix rendering setting like Wireframe for cubes, Flat Shading for bumpy cubes, and Phong Shading for bunnies. Or we have to use keyboard to switch its rendering setting. Thanks in advance.

**Comment by danielepanozzo** [comment]
You can use triangles to represent the cube.

Each object should have its own rendering setting and a scene might contain multiple objects with different rendering settings.
