### ISSUE TITLE
Assignment 3 About the Clicking

### ISSUE THREAD

**Issue by tomhsu1990** [danielepanozzo/cg-old#37]
Hi,
I have a question about clicking the object. Since we need to do all transformations in the shader, when we are going to implement the clicking operation, we are also not allowed to do the transformation. Is it possible to let the shader output the clicked object?

Thanks.

**Comment by danielepanozzo** [comment]
For the picking, you can do the inverse transformations on the CPU side. It is mandatory to do the transformations in the shaders only for the rendering.
