### ISSUE TITLE
Orthographic projection

### ISSUE THREAD

**Issue by jbour20** [danielepanozzo/cg-old#39]
I'm having some issues constructing the orthographic projection matrix for assignment 3. Both the book and notes say to consider the camera as viewing in the -z direction, and that for the viewing box defined by the near-left point (l,b,n) and far-right point (r,t,f), the value of f should therefore be "more negative" than n. This, however, causes all objects in my scene to become inverted, and the only fix I've found is to take the absolute value of these z-coordinates. 

There's a brief section in the book that says OpenGL has users specify absolute values for n and f. This is consistent with the API's description of the gluPerspective function which is based on z-distance from the camera, rather than coordinates in camera space. Is it necessary then to always consider absolute z-values for this transformation?

**Comment by danielepanozzo** [comment]
As we discussed today in the class, opengl has a different convention for the z direction than what I presented in the slides. You should flip the z coordinate in the orthographic projection.
