### ISSUE TITLE
Proper data structure for RGB color map

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/cg-old#4]
Is there a recommended data structure using Eigen for an RGB color map?

If so, how would we, in a single operation, insert an RGB color into an x and y position?

Or should we just be storing R, G, and B in separate matrixes?

**Comment by danielepanozzo** [comment]
Unfortunately Eigen does not directly support matrices with three dimensions (or if you want 2D matrices of vectors). I recommend to use 4 matrices, one for each channel. 

Another way to do it is by templating a Eigen matrix with a Eigen vector, but it is not officially supported by the Eigen developers.
