### ISSUE TITLE
question about texture mapping

### ISSUE THREAD

**Issue by ll1733** [danielepanozzo/cg-old#53]
I implemented texture mapping for my object, but the texture seems not exactly on the correct position. To be more specific, each texture pixel appears slightly off center in x axis. At first, I thought it was index mismatching issue. So I adjusted the indices for refering to "vt" (e.g: +1 or -1), but then, the texture turned out to be completely wrong. Could you suggest any possible issue that I may have encountered?

**Comment by ll1733** [comment]
To load the image, I converted the image from its original format to bmp. Do you think it may related to the problem?

**Comment by danielepanozzo** [comment]
It is very hard to tell, could you post a screenshot?

One common mistake is to have a flip in one of the axis. Could it be that your texture is "almost" symmetric on x but not completely and you have the x axis flipped?
