### ISSUE TITLE
Normal direction of triangles in opposite direction as light.

### ISSUE THREAD

**Issue by oveddan** [danielepanozzo/cg-old#6]
Since the normal direction on a triangle depends on the order of the verteces, that means the normal will just point on one side of the surface and not the other.  If a light then is pointing at the back of a triangle surface, where the normal is not pointing out of, is it correct that it should not affect the shading of that surface?

**Comment by danielepanozzo** [comment]
Yes, it is common to hide the "back side" of the triangles of a closed surface.
https://en.wikipedia.org/wiki/Back-face_culling
