### ISSUE TITLE
Corrupted bumpy cube?

### ISSUE THREAD

**Issue by AIR20** [danielepanozzo/cg-old#65]
I don't know if it's intentional or not but it's somehow unexpected. I found that the file `bumpy_cube.off` have quite a few triangles that degenerate to a line.

For example, face 151 has vertices 252 253 385 while vertex 252 and vertex 385 are exactly the same.

**Comment by danielepanozzo** [comment]
This is strange, I just checked with meshlab and the mesh seems to be valid, with no duplicate vertices or degenerate faces:

<img width="353" alt="screen shot 2017-12-04 at 10 15 56 am" src="https://user-images.githubusercontent.com/6785134/33559925-4ef0d5ce-d8dc-11e7-8a98-a2e080154db5.png">

Could you double check your off reader? It could be that the vertices are very close and you round them up to the same position.

**Comment by AIR20** [comment]
I think I found the problem. They are not the same vertices. But only the sign of the z coordinate are different. It causes problem because it is parallel to my ray while the solver still gives valid solutions, which allows me to select some outside regions.
