### ISSUE TITLE
Simple question regarding light source

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#69]
[Forgive me if my question is stupid]

If there is a single light source, are we assuming that this light source emits light rays in every direction until the light ray hits some surface? Or are we assuming that the light rays are parallel?

Thank you

**Comment by danielepanozzo** [comment]
In the simple ray tracing renderer that we studied in class, we do not trace the rays starting from the light. We trace the rays starting from the eye to find the first object that is visible in a certain pixel. The light is then use after we compute the intersection, to compute the color of the pixel.

**Comment by LihengGong** [comment]
Thank you professor. That's very helpful.
