### ISSUE TITLE
When to modify/use part1 code

### ISSUE THREAD

**Issue by ericapeng** [danielepanozzo/cg-old#7]
I don't really understand when to modify/use the code in part1. Does the png outputted in part2 represent how the objects look in the canonical view volume, so we have to transform them into screen space? (the png output in part1)

**Comment by danielepanozzo** [comment]
Part1: this is just a simple example to show you how to use the provided function that writes a png file.  You don't have to use this code in the exercise.
Part2: In ray tracing, there is no need to explicitly map the scene to a canonical view volume, you can do everything in world coordinates. Part2 is a minimal but complete raytracer that uses orthographic projection and renders a sphere. All the material that you need for this exercise is in the first two lectures (and corresponding book chapters) --- you can use the matrix transformations that we saw in the last lecture if you want, but they are not necessary for this exercise.
