### ISSUE TITLE
[Assignment 1] if condition regarding the example program

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#70]
In part 2 in the example program, there is one `if` condition

```C++
 if (ray_on_xy.norm()<sphere_radius)
            {
                // The ray hit the sphere, compute the exact intersection point
                Vector3d ray_intersection(ray_on_xy(0),ray_on_xy(1),
                        sqrt(sphere_radius*sphere_radius - ray_on_xy.squaredNorm()));
                .....
           }
```
Question is: Is this `if` condition just an optimization or is it part of the ray tracing algorithm?  
My understanding from the lecture notes is that for orthographic, all the ray’s starting points formed a square instead of a circle.

Thank you

**Comment by hankstag** [comment]
yes, it's just a simple way to test whether the ray intersects with the sphere in the example case; you need to modify it

**Comment by LihengGong** [comment]
Thank you.
