### ISSUE TITLE
Is it okay to move around/scale the objects?

### ISSUE THREAD

**Issue by mun1r0b0t** [danielepanozzo/cg-old#72]
After loading the bumpy_cube mesh, it hides my entire scene and also doesn't fit into my image plane. Is it okay if I scale it down and move it somewhere else in the scene? Is it okay to apply these while reading the vertices or should I use affine transformations?

**Comment by hankstag** [comment]
hi, it's not required to use affine transformations, you can scale it and move it as you like after reading in the model

**Comment by mun1r0b0t** [comment]
Thanks.
