### ISSUE TITLE
[Assignment 1] line - sphere intersection: which root should be kept for the quadratic equation ?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#73]
The text book states:
> If the discriminant is positive, there are two solutions: one solution where the ray enters
the sphere and one where it leaves.

Question is: 
- Which root should be kept?
- How do we know which one is where the ray enters and which one is where the ray leaves?

**Comment by hankstag** [comment]
yes, if there are two intersection points then you should pick the one that's closer to the camera
