### ISSUE TITLE
[Assignment 1] Are we supposed to plug the solution back into the ray function p(t) = e + td to find the plot of the intersection point?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#74]
For line-sphere intersection, after we solve the quadratic equation, since the solution is only a scalar, are we supposed to plug the scalar solution back into the ray function p(t) = e + td to find the plot(i.e. x, y, z) of the intersection point?

**Comment by hankstag** [comment]
yes, if you plug the solution back, you will get the position of the intersection point
