### ISSUE TITLE
[Assignment 1] Question about Orthographic View

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#75]
For Orthographic View, suppose line equation is
p(t) = e + td

Sphere is:
(p - c)·(p - c) = R^2

Then d is parallel to axis z, and e is in x-y plane, so that
e·d = 0 ?

**Comment by danielepanozzo** [comment]
Hi,
I don't understand the question, could you please elaborate? The only difference between Orthographic and Perspective is how you generate the rays: the intersection code should be the same. For the assignment, you should not make any assumption on d and e.

**Comment by LihengGong** [comment]
Thank you. I'll talk to you then.

**Comment by LihengGong** [comment]
Just add one comment:
I was trying to understand the provided example program so that I can understand how ray tracing algorithm works in source code's perspective.

My understanding of the provided example is that 
- the sphere is centered in the original(0, 0, 0)
- using orthographic view, the direction of the ray(call it *`d`*) is parallel to axis *`z`*
- camera location(call it *`e`*) is in (x, y) plane(or plane z=0)  so that *`z · e`* = 0.

From the above, the determinate of the example is written as:
```C
sqrt(sphere_radius*sphere_radius - ray_on_xy.squaredNorm())
```

**Comment by LihengGong** [comment]
My guess is that the answer is yes.
Will close this for now.

**Comment by danielepanozzo** [comment]
Yes, that's correct.
