### ISSUE TITLE
Error when doing determinant() and colPivHouseholderQR()

### ISSUE THREAD

**Issue by pondjames007** [danielepanozzo/cg-old#79]
When solving the equation of mesh intersection, both determinant() and colPivHouseholderQR() come up with error. I even use the example code shown in the slide and it still come up with the error.

    Matrix3d A;
    Vector3f b;
    A << 5,3,-7,  -3,5,12,  9,-2,-2;
    b << 4, 9, -3;
    Vector3f x = A.colPivHouseholderQr().solve(b);
    cout<<A.determinant()<<endl;

For determinant(), the error shows:

> Undefined symbols for architecture x86_64:
  "Eigen::MatrixBase<Eigen::Matrix<float, 3, 3, 0, 3, 3> >::determinant() const", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64

For colPivHouseholderQR(), the error shows:
> implicit instantiation of undefined template
      'Eigen::ColPivHouseholderQR<Eigen::Matrix<float, 3, 3, 0, 3, 3> >'
        Vector3f X = A.colPivHouseholderQr().solve(B);
/Users/pondjames007/Desktop/ITP_Classes/ComputerGraphics/Assignment_1/../ext/eigen/Eigen/src/Core/util/ForwardDeclarations.h:222:37: note:
      template is declared here
template<typename MatrixType> class ColPivHouseholderQR;

I have no idea what's happening.

Thanks in advance!

**Comment by hankstag** [comment]
Hi,
Did you include the header file?
#include <Eigen/Dense>

**Comment by pondjames007** [comment]
OK it works!

By the way, I want to know which method is better to solve the equation?
using direct solver or cramer's rule?

Thanks!

**Comment by iamnwi** [comment]
I think using cramer's rule is faster, at least it is in my code.

**Comment by danielepanozzo** [comment]
Cramer's rule is faster but less numerically stable than a direct solver. For this specific case, numerical stability is not so important, so the overall better way to proceed is Cramer's rule.
