### ISSUE TITLE
perspective projection

### ISSUE THREAD

**Issue by jw3877** [danielepanozzo/cg-old#8]
1) For the perspective projection, should we just choose an arbitrary point e?

2) The value given to us in the original program:
 Vector3d ray_origin = origin + double(i)_x_displacement + double(j)_y_displacement;

is still good and becomes point s as shown in Figure 4.6?

3) The value:
 Vector3d origin(-1,1,1);

stays the same for either type of projection?

**Comment by danielepanozzo** [comment]
1) Yes. e contributes in determining what part of the scene you will see, you will have to pick a point that allows you to see all the objects in your scene.
2,3) The rays in orthographic projection have different origins but the same direction. In perspective projection they have the same origin but different directions. You will have to adapt the code accordingly.
