### ISSUE TITLE
Can we move the position of light using translation?

### ISSUE THREAD

**Issue by peiyueY** [danielepanozzo/cg-old#82]
I notice that light_position is "const". So I'm not sure whether it means that we are not supposed to change it. Thanks!

**Comment by danielepanozzo** [comment]
const is just a useful keyword in c++ to avoid mistakes. The compiler will give you an error if you try to change a const variable. In the example I provided, the light does not move, so I defined it as const. To move the light in your assignment you will have to remove const.
