### ISSUE TITLE
1.5 shadow ray

### ISSUE THREAD

**Issue by peiyueY** [danielepanozzo/cg-old#83]
Hi, I have a question about the shadow ray. Is it from each intersection to the light or from each pixel to the light?

In the powerpoint of chapter2, page 25 shadow part, if a ray have intersection with both blue sphere and purple sphere, because the intersection of purple sphere is closer to the light, the color of the pixel will only be determined by the color of purple sphere's intersection and the shadow ray from the intersection will never intersect with other items.

But if the  shadow ray is from each pixel to the light, then there will be shadow on the "floor", which is visible.

Thanks

**Comment by danielepanozzo** [comment]
The shadow ray is cast from the intersection point p to the light l (not from the pixel position). if you do not find any intersection between p and l, you add the contribution of l to the color, otherwise you don't do anything. You need to cast one shadow ray *for each light* in your scene.
