### ISSUE TITLE
[Assignment 1] Setting up travis CI badge

### ISSUE THREAD

**Issue by mun1r0b0t** [danielepanozzo/cg-old#85]
The assignment submission requirements say "Follow further instructions to set up travis badge". How do I set it up? Right now, it just says Unknown.

**Comment by hankstag** [comment]
Hi,
To show the badge correctly, you need to update the first line in the README.md file.

In the README.md file of your current repo, there is this line: 

> #Assignment_1\[!\[BuildStatus](link_a)](link_b)
 - link_a should be the link to the badge of your repo in the Travis CI website
![screen shot 2018-10-06 at 8 57 35 pm](https://user-images.githubusercontent.com/6883726/46577072-966ab900-c9aa-11e8-8cc3-67450ea6fa86.png)
To get the link, please press the mark in the red rectangle shown above. You can copy it from the new window pops up.
![screen shot 2018-10-06 at 9 00 15 pm](https://user-images.githubusercontent.com/6883726/46577074-d92c9100-c9aa-11e8-8bba-8ab5bdc1c32b.png)

- link_b should be 
>https://travis-ci.com/NYUGraphics/YOUR_REPO_NAME
in this case, `YOUR_REPO_NAME` should be `assignment1-YOUR_USER_NAME`

**Comment by mun1r0b0t** [comment]
Thank you.
