### ISSUE TITLE
How to add TBB to the project

### ISSUE THREAD

**Issue by iamnwi** [danielepanozzo/cg-old#87]
Hi, my program can be built in my own machine, but it failed on Travis CI because TBB is not found. How can I add TBB to my project on Travis CI?

**Comment by danielepanozzo** [comment]
It is a bit tricky to get TBB to compile with travis, it is ok if you disable TBB for the travis build. If you want to try, here is an example of how to make it work:
https://github.com/wjakob/instant-meshes
