### ISSUE TITLE
Any hint on normal of ray-triangle intersection ?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#88]
For ray-sphere intersection, the computation of normal is straightforward, it is pointing from sphere center to the intersection point, but for triangle, although normal is also straightforward(a cross product), the direction of this normal is confusing.

Would you please kindly give any hint on the direction of the normal of ray-triangle intersection ?

**Comment by danielepanozzo** [comment]
The triangles in the provided mesh files are all oriented consistently, i.e. if you take the dot product between the edge between vertices 1 and 2 of every triangle, and the edge between vertices 2 and 3 of every triangle, you will consistently get a normal pointing inside (or outside, I don't remember what is the convention used for off files).

**Comment by LihengGong** [comment]
Thanks. That helps me a lot.
