### ISSUE TITLE
I feel like the Specular shading ball is not right

### ISSUE THREAD

**Issue by TrojanFighter** [danielepanozzo/cg-old#89]
I am moving forward but...
![image](https://user-images.githubusercontent.com/12609168/46637833-ecb33580-cb2b-11e8-83e2-43904725cd5e.png)
My shading attempt felt weird. The left bottom one is the specular one and it has huge colored parts outside the black areas. 
Also I don’t know what should be the right value range of ambient light(affected the right bottom one), -1 or 1 maybe?

**Comment by TrojanFighter** [comment]
In my MakeSphere() I used 
				Vector3d RValue = 2 * (ray_normal.dot(LightDirection))*ray_normal - LightDirection;
				double Specular1 = pow(RValue.dot(cameraDirection.light_direction), 10);
to calculate Specular value.

**Comment by danielepanozzo** [comment]
The ambient light component should have a much smaller impact than the other two. A weight of 0.1 or 0.2 (out of 1) is usually a good choice. The specular highlight looks indeed strange. Could it be that you forgot to normalize some of your vectors?

**Comment by TrojanFighter** [comment]
Oh I guess this might be right?
![image](https://user-images.githubusercontent.com/12609168/46638063-14ef6400-cb2d-11e8-8401-2131da900e2d.png)

It looks I misuse the vector from light source to point as" light direction"
