### ISSUE TITLE
[Assignment 2] Questions on scaling and color mode

### ISSUE THREAD

**Issue by mun1r0b0t** [danielepanozzo/cg-old#91]
1. For scaling the triangles in 1.2, should we scale up or down by 25% of the initial size each time, or will it be 25% of current size? So, if a triangle is scaled up twice, should the final size be 1.5x the initial size or 1.5625x (1.25 * 1.25) times the initial size. Also, is it % of overall area `(Sx = Sy = sqrt(scaling))` or % of dimensions `(Sx = Sy = scaling)`?

2. Same questions as above for zooming in section 1.4

3. For colour mode, should the click be inside the triangle or should we check for the closest point regardless of where the click happened?

**Comment by danielepanozzo** [comment]
1. Since it is not specified, all options you listed are ok.
2. Since it is not specified, all options you listed are ok.
3. It should pick the closest point regardless of where the click happened.
