### ISSUE TITLE
[OpenGL Coordinates] Which coordinate(s) is(are) normalized?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#92]
Several spaces are mentioned in our classnotes:
- object space
- world space
- cameral space
- canonical view volume
- screen space

My understanding is that `screen space` corresponds to screen pixels(e.g. `1024 * 768`), 
`canonical view volume` is apparently normalized(the normalized cube), but I'm not sure whether `cameral space`, `world space`, `object space` is normalized or not.

Thank you

**Comment by danielepanozzo** [comment]
You do not have control of the "object space": it is simply what you get from the files that you load. For the world and camera space, you can decide what units you use, it is up to you. The important part is that when you transform the camera space into the canonical view volume, you have to map the part of the scene that you want to see inside the normalized cube (-1,-1,-1) to (1,1,1).

**Comment by LihengGong** [comment]
Got your idea. Thank you prof.
