### ISSUE TITLE
2.1 Are we supposed to insert multiple triangles?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#93]
1. If we are supposed to insert multiple triangles, is there any limitation on the total number of triangles inserted?

2. Are we supposed to consider overlapping triangles for the translation mode? For example, if two triangles overlaps each other, when the mouse clicks the overlapping area, should both triangles be selected?

Thank you.

**Comment by danielepanozzo** [comment]
1. No there is no limit on how many triangles can be inserted.

2. If two triangles overlap and you click on the overlap, your program should select one of the two, it does not matter which one.

**Comment by LihengGong** [comment]
Thank you prof.
