### ISSUE TITLE
[General question] What is the relationship between this class(CG) and Geometric Modeling?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#94]
(Apologize if this question is not relevant).

Dear Professor,
I love this CG class and I found that there is another class named "Geometric Modeling(GM)" in 19Spring and I'm considering taking it then, but I'm not sure what is the relationship between CG and GM? I mean, do these two classes overlap in the content? If most of the class content overlaps, I think just taking CG is good for me.

Thank you

**Comment by danielepanozzo** [comment]
Hi,

glad to hear that you are enjoying the CG class. The GM class is very different, the overlap is minimal with only a few algorithms on harmonic parametrization and on space deformation which are covered in both classes. You can take a look at the GM class slides from last year at this url: https://github.com/danielepanozzo/gp

**Comment by LihengGong** [comment]
Thank you prof. That's very helpful.
