### ISSUE TITLE
Link error code 2019 during the build

### ISSUE THREAD

**Issue by TrojanFighter** [danielepanozzo/cg-old#96]
I tries to check if mouse is inside a triangle and wrote this:

bool CheckPointInsideTriangle(double x, double y, Eigen::MatrixXf triangle)
{
	
	Eigen::Vector3d pointToDetect(x, y,0);
	
	Eigen::Matrix3d triangle3d;
	triangle3d.col(0)[0] = triangle.col(0)[0];
	triangle3d.col(0)[1] = triangle.col(0)[1];
	triangle3d.col(0)[2] = 0;
	triangle3d.col(1)[0] = triangle.col(1)[0];
	triangle3d.col(1)[1] = triangle.col(1)[1];
	triangle3d.col(1)[2] = 0;
	triangle3d.col(2)[0] = triangle.col(2)[0];
	triangle3d.col(2)[1] = triangle.col(2)[1];
	triangle3d.col(2)[2] =0;
	//return true;
	
	double result1 = (triangle3d.col(0)- triangle3d.col(1)).cross(pointToDetect- triangle3d.col(1))[2];
	double result2 = (triangle3d.col(1) - triangle3d.col(2)).cross(pointToDetect- triangle3d.col(2))[2];
	double result3 = (triangle3d.col(2) - triangle3d.col(0)).cross(pointToDetect- triangle3d.col(0))[2];
	if(result1>0&&result2>0&&result3>0)
	{
		return true;
	}
	return false;
}

When building there is error like:

Error	LNK2019	unresolved external symbol "public: class Eigen::Matrix<double,3,1,0,3,1> __thiscall Eigen::MatrixBase<class Eigen::CwiseBinaryOp<struct Eigen::internal::scalar_difference_op<double>,class Eigen::Block<class Eigen::Matrix<double,3,3,0,3,3>,3,1,1> const ,class Eigen::Block<class Eigen::Matrix<double,3,3,0,3,3>,3,1,1> const > >::cross<class Eigen::CwiseBinaryOp<struct Eigen::internal::scalar_difference_op<double>,class Eigen::Matrix<double,3,1,0,3,1> const ,class Eigen::Block<class Eigen::Matrix<double,3,3,0,3,3>,3,1,1> const > >(class Eigen::MatrixBase<class Eigen::CwiseBinaryOp<struct Eigen::internal::scalar_difference_op<double>,class Eigen::Matrix<double,3,1,0,3,1> const ,class Eigen::Block<class Eigen::Matrix<double,3,3,0,3,3>,3,1,1> const > > const &)const " (??$cross@V?$CwiseBinaryOp@U?$scalar_difference_op@N@internal@Eigen@@$$CBV?$Matrix@N$02$00$0A@$02$00@3@$$CBV?$Block@V?$Matrix@N$02$02$0A@$02$02@Eigen@@$02$00$00@3@@Eigen@@@?$MatrixBase@V?$CwiseBinaryOp@U?$scalar_difference_op@N@internal@Eigen@@$$CBV?$Block@V?$Matrix@N$02$02$0A@$02$02@Eigen@@$02$00$00@3@$$CBV43@@Eigen@@@Eigen@@QBE?AV?$Matrix@N$02$00$0A@$02$00@1@ABV?$MatrixBase@V?$CwiseBinaryOp@U?$scalar_difference_op@N@internal@Eigen@@$$CBV?$Matrix@N$02$00$0A@$02$00@3@$$CBV?$Block@V?$Matrix@N$02$02$0A@$02$02@Eigen@@$02$00$00@3@@Eigen@@@1@@Z) referenced in function "bool __cdecl CheckPointInsideTriangle(double,double,class Eigen::Matrix<float,-1,-1,0,-1,-1>)" (?CheckPointInsideTriangle@@YA_NNNV?$Matrix@M$0?0$0?0$0A@$0?0$0?0@Eigen@@@Z)	Assignment2_bin	F:\CPPProject\assignment2-TrojanFighter\build\main.obj	1

**Comment by danielepanozzo** [comment]
https://eigen.tuxfamily.org/dox/group__QuickRefPage.html

Whenever you use cross you need to add
```
#include <Eigen/Geometry>
```

**Comment by TrojanFighter** [comment]
Solved
