### ISSUE TITLE
[Assignment 2] 1.5 add keyframing: is the transformation required to happen in the shader(GPU side)?

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#98]
For task 1.5 add keyframing, is there any requirement that the transformation(scaling, translation, rotation) should happen in shader(GPU side) or can we also make transformation on CPU side?

Thank you

**Comment by danielepanozzo** [comment]
It is ok if you do the transformation on the CPU.

**Comment by LihengGong** [comment]
Thank you Prof.
