### ISSUE TITLE
Do we have a second demo date for assignment 2

### ISSUE THREAD

**Issue by LihengGong** [danielepanozzo/cg-old#99]
Dear Prof,

Do we have a second demo date for assignment 2 or should we just push the source code and note to github?

Thank you

**Comment by hankstag** [comment]
Hi,

Yes, there are two demo sessions next week. Please select a time slot [here](https://docs.google.com/spreadsheets/d/1Y8rQaP47qMl39WWn7BTwnwQrYZcmegSrQJv1Qe9Tyxw/edit?usp=sharing).
